fn main() -> Result<(), csv::Error> {
    println!("[Main] Soy parte 2");
    Ok(())
}
